name: step1
description: 'step 1 to go next'
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  bootstrap_sass: ^4.1.2
  
dev_dependencies:
  angular_test: ^2.0.0
  test: ^1.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.3
  sass_builder: ^2.1.1