name: step1
description: 'step 1 to go next'
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  rst_bootstrap: ^4.2.1
  
dev_dependencies:
  angular_test: ^2.0.0
  test: ^1.3.3
  build_runner: ^1.0.0
  build_test: ^0.10.3+1
  build_web_compilers: ^1.0.0
  sass_builder: ^2.1.2